version: '3.8'

services:
  kafka:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  mongodb:
    container_name: turkcell-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb2:
    container_name: turkcell-invoicedb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb2_data:/data/db

  mysqldb:
    container_name: maintenance-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=maintenance-db
      - MYSQL_USER=mysql
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysqldb_data:/data/db



volumes:
  kafka_data:
  mongodb_data:
  mysqldb_data:
  mongodb2_data:
